name: mag
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pycairo
  - python=3.7.*
  - pytorch=1.1.*
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - pip:
    - tqdm
    - pillow
    - seaborn